if (typeof translations === 'undefined') translations = [];
translations['en_US'] = 
{
   "domain": "messages",
   "locale_data": {
      "messages": {
         "": {
            "domain": "messages",
            "plural_forms": "nplurals=2; plural=(n != 1);",
            "lang": "en_US"
         },
         "Online Voting: anonymous ballots and traceable": [
            "Online Voting: anonymous ballots and traceable"
         ],
         "Open a new voting": [
            "Open a new voting"
         ],
         "Take part in a voting": [
            "Take part in a voting"
         ],
         "Fetch result": [
            "Fetch result"
         ],
         "Procedure": [
            "Procedure"
         ],
         "Show explanations and technical information": [
            "Show explanations and technical information"
         ],
         "%s has rejected your request (error no  %d):\n %s": [
            "%s has rejected your request (error no  %d):\n %s"
         ],
         "Voting certificate %s": [
            "Voting certificate %s"
         ],
         "In order to be able to cast your vote, you have to save your voting certificate on your device now": [
            "In order to be able to cast your vote, you have to save your voting certificate on your device now"
         ],
         "Creating voting certificate": [
            "Creating voting certificate"
         ],
         "<ul><li>You will get voting certificae in the form of a webpage file as result of this step.</li><li>Please remember where you saved it.</li><li>The voting certificate is neccesary in order to cast the vote. There is no way getting a replacement for it. Thus, save it securely till the end of the voting.</li></ul>": [
            "<ul><li>You will get voting certificae in the form of a webpage file as result of this step.</li><li>Please remember where you saved it.</li><li>The voting certificate is neccesary in order to cast the vote. There is no way getting a replacement for it. Thus, save it securely till the end of the voting.</li></ul>"
         ],
         "<p><h2>Technical information</h2>The voting certificate is digitally signed by at least two servers. This signatures makes the certificate valid for voting. <br> The voting certificate contains an unique certificate number which is only known by your device - it was generated by your device and encrypted before it was sent and signed by the servers. Your device decrypts thes certificate number together with the server's signatures (This procedure is called &quot;Blinded Signature&quot;). Thus, the servers do not know the certificate number. <br> You can imagine it as follows:<br>  Your device generates a long random number (a unique number) and writes it on a sheet of paper. Your device lays a sheet of carbon-paper on this sheet, puts them together in an envelope, seals it and sends it to the servers. The servers sign on the outside of the envelope, in case you are entitled to vote. By doing so, the signature is transferred to the sheet containing the certificate number because of the carbon-paper. The servers do not open the envelope (which they cannot do, because they do not know the needed key), and send the envelope back to your device. Your device opens (decrypts) the envelope. In result, your device has a sheet of paper containing a unique certificate number and the signatures of the servers, but the servers do not know this number.The unique number together with the server's signatures and the ballot is calles >voting certificate<.</p>": [
            "<p><h2>Technical information</h2>The voting certificate is digitally signed by at least two servers. This signatures makes the certificate valid for voting. <br> The voting certificate contains an unique certificate number which is only known by your device - it was generated by your device and encrypted before it was sent and signed by the servers. Your device decrypts thes certificate number together with the server's signatures (This procedure is called &quot;Blinded Signature&quot;). Thus, the servers do not know the certificate number. <br> You can imagine it as follows:<br>  Your device generates a long random number (a unique number) and writes it on a sheet of paper. Your device lays a sheet of carbon-paper on this sheet, puts them together in an envelope, seals it and sends it to the servers. The servers sign on the outside of the envelope, in case you are entitled to vote. By doing so, the signature is transferred to the sheet containing the certificate number because of the carbon-paper. The servers do not open the envelope (which they cannot do, because they do not know the needed key), and send the envelope back to your device. Your device opens (decrypts) the envelope. In result, your device has a sheet of paper containing a unique certificate number and the signatures of the servers, but the servers do not know this number.The unique number together with the server's signatures and the ballot is calles >voting certificate<.</p>"
         ],
         "Please load the voter certification file": [
            "Please load the voter certification file"
         ],
         "<h2>Voting certificate generated.</h2><p id=\"didSaveButtonsId\">Did you save the voting certificate on your devide?<br><button id=\"savedReturnEnvelope\" onclick=\"page.blinder.onUserDidSaveReturnEnvelope();\" >Yes</button>&emsp;<button id=\"didNotSaveReturnEnvelope\" onclick=\"page.blinder.saveReturnEnvelope();\" >No</button></p><p><ul id=\"howToVoteId\" style=\"display:none\"><li>You got a voting certificate in the form of a webpage file which you saved on your device.</li><li>Please remember the place where you saved it.</li><li>The voting certificate is needed in order to cast the vote. There is no way obaining a new one. Thus, save it securly till the end of the voting.</li><li>In order to cast a vote, open the voting certificate in a web browser. You can do this by double clicking it in the file explorer.</li><li>Everyone who has the voting certificate can use it to cast the vote - thus do not pass it on someoneCasting the vote using the voting certificate is anonymous. That means, as long as you do not help, nobody can find out who sent the vote.</li><li>%s</li></ul></p>": [
            "<h2>Voting certificate generated.</h2><p id=\"didSaveButtonsId\">Did you save the voting certificate on your devide?<br><button id=\"savedReturnEnvelope\" onclick=\"page.blinder.onUserDidSaveReturnEnvelope();\" >Yes</button>&emsp;<button id=\"didNotSaveReturnEnvelope\" onclick=\"page.blinder.saveReturnEnvelope();\" >No</button></p><p><ul id=\"howToVoteId\" style=\"display:none\"><li>You got a voting certificate in the form of a webpage file which you saved on your device.</li><li>Please remember the place where you saved it.</li><li>The voting certificate is needed in order to cast the vote. There is no way obaining a new one. Thus, save it securly till the end of the voting.</li><li>In order to cast a vote, open the voting certificate in a web browser. You can do this by double clicking it in the file explorer.</li><li>Everyone who has the voting certificate can use it to cast the vote - thus do not pass it on someoneCasting the vote using the voting certificate is anonymous. That means, as long as you do not help, nobody can find out who sent the vote.</li><li>%s</li></ul></p>"
         ],
         "Error: voting certificate data not found": [
            "Error: voting certificate data not found"
         ],
         "Error: voting certificate data could not be read: JSON decode failed": [
            "Error: voting certificate data could not be read: JSON decode failed"
         ],
         "The voter certificate is not consistent": [
            "The voter certificate is not consistent"
         ],
         "The signature on the vote is correct. This means that the vote is unchanged.": [
            "The signature on the vote is correct. This means that the vote is unchanged."
         ],
         "The signature on the vote is not correct. This means that the vote is changed or the key does not match.": [
            "The signature on the vote is not correct. This means that the vote is changed or the key does not match."
         ],
         "The number of signatures on the voting certificate is not correct. \nRequired number: %d, number in this voting certificate: %d: ": [
            "The number of signatures on the voting certificate is not correct. \nRequired number: %d, number in this voting certificate: %d: "
         ],
         "The signature by the permission server >%s< for the voting key is correct. This means, the server has confirmed that the according voter is entitled to vote.": [
            "The signature by the permission server >%s< for the voting key is correct. This means, the server has confirmed that the according voter is entitled to vote."
         ],
         "The signature by permission server >%s< for the voting key is not correct. Either the configuration is wrong or there is a fraud. Please inform the persons responsible for the voting": [
            "The signature by permission server >%s< for the voting key is not correct. Either the configuration is wrong or there is a fraud. Please inform the persons responsible for the voting"
         ],
         "Error verifying the signature:\n%s": [
            "Error verifying the signature:\n%s"
         ],
         "For voter >%s< the server >%s< returns a different order of signatures than server >%s<.": [
            "For voter >%s< the server >%s< returns a different order of signatures than server >%s<."
         ],
         "Step 1: Enter voting link": [
            "Step 1: Enter voting link"
         ],
         "Step 2: Authorize": [
            "Step 2: Authorize"
         ],
         "Step 3: Vote": [
            "Step 3: Vote"
         ],
         "Enter Voting Link": [
            "Enter Voting Link"
         ],
         "<p><ul><li>I yet do not have a voting certificate</li><li>For this voting no voting certificate is needed</li><li>I do not know wheather a voting vertificate is needed</li></ul>": [
            "<p><ul><li>I yet do not have a voting certificate</li><li>For this voting no voting certificate is needed</li><li>I do not know wheather a voting vertificate is needed</li></ul>"
         ],
         "Fetch voting properties": [
            "Fetch voting properties"
         ],
         "I already have a voting certificate": [
            "I already have a voting certificate"
         ],
         "Take part in voting": [
            "Take part in voting"
         ],
         "It is not possible anymore to create a voting certificate": [
            "It is not possible anymore to create a voting certificate"
         ],
         "The voting requires election module >%s< which is not supported by this client.\nUse a compatible client.": [
            "The voting requires election module >%s< which is not supported by this client.\nUse a compatible client."
         ],
         "Name of voting:": [
            "Name of voting:"
         ],
         "The voting requires authorisation module >%s< which is not supported by this client.\nUse a compatible client.": [
            "The voting requires authorisation module >%s< which is not supported by this client.\nUse a compatible client."
         ],
         "Generate voting certificate and save it": [
            "Generate voting certificate and save it"
         ],
         "Voting mode >%s< is not supported by this client": [
            "Voting mode >%s< is not supported by this client"
         ],
         "The voting certificate is not valid": [
            "The voting certificate is not valid"
         ],
         "You directly opened the voting certificate, but you have to save it as file on your device.": [
            "You directly opened the voting certificate, but you have to save it as file on your device."
         ],
         "Error r83g83": [
            "Error r83g83"
         ],
         "You can cast your vote from now on and without any time limit.": [
            "You can cast your vote from now on and without any time limit."
         ],
         "You can cast your vote from now on until before %s.": [
            "You can cast your vote from now on until before %s."
         ],
         "You can cast your vote from %s until before %s.": [
            "You can cast your vote from %s until before %s."
         ],
         "It is not possible anymore to cast your vote.": [
            "It is not possible anymore to cast your vote."
         ]
      }
   }
}; 
