if (typeof translations === 'undefined') translations = [];
translations['de'] = 
{
   "domain": "messages",
   "locale_data": {
      "messages": {
         "": {
            "domain": "messages",
            "plural_forms": "nplurals=2; plural=(n != 1);",
            "lang": "de"
         },
         "Online Voting: anonymous ballots and traceable": [
            "Online Abstimmung: anonym und nachvollziehbar"
         ],
         "Open a new voting": [
            "Neue Abstimmung anlegen"
         ],
         "Take part in a voting": [
            "An Abstimmung teilnehmen"
         ],
         "Fetch result": [
            "Ergebnis abrufen"
         ],
         "Procedure": [
            "So geht's"
         ],
         "Show explanations and technical information": [
            "Erklärungen und technische Informationen anzeigen"
         ],
         "%s has rejected your request (error no  %d):\n %s": [
            "%s hat Ihr Anliegen zurückgewiesen (Fehlernr. %d):\n%s"
         ],
         "Voting certificate %s": [
            "Wahlschein %s"
         ],
         "In order to be able to cast your vote, you have to save your voting certificate on your device now": [
            "Damit Sie später Ihre Stimme senden können, müssen Sie jetzt den Wahlschein als Datei auf Ihrem Gerät abspeichern."
         ],
         "Creating voting certificate": [
            "Erstelle Wahlschein"
         ],
         "<ul><li>You will get voting certificae in the form of a webpage file as result of this step.</li><li>Please remember where you saved it.</li><li>The voting certificate is neccesary in order to cast the vote. There is no way getting a replacement for it. Thus, save it securely till the end of the voting.</li></ul>": [
            "<ul>\n\t<li>Als Ergebnis dieses Schrittes erhalten Sie einen Wahlschein in Form einer Webseiten-Datei.</li>\n\t<li>Merken Sie sich bitte, wo Sie die Datei speichern.</li>\n\t<li>Der Wahlschein wird benötigt, um die Stimme abzugeben und kann nicht ersetzt werden. Daher wird empfohlen, den Wahlschein bis zum Ende der Abstimmung zu sichern.</li>\n</ul>"
         ],
         "<p><h2>Technical information</h2>The voting certificate is digitally signed by at least two servers. This signatures makes the certificate valid for voting. <br> The voting certificate contains an unique certificate number which is only known by your device - it was generated by your device and encrypted before it was sent and signed by the servers. Your device decrypts thes certificate number together with the server's signatures (This procedure is called &quot;Blinded Signature&quot;). Thus, the servers do not know the certificate number. <br> You can imagine it as follows:<br>  Your device generates a long random number (a unique number) and writes it on a sheet of paper. Your device lays a sheet of carbon-paper on this sheet, puts them together in an envelope, seals it and sends it to the servers. The servers sign on the outside of the envelope, in case you are entitled to vote. By doing so, the signature is transferred to the sheet containing the certificate number because of the carbon-paper. The servers do not open the envelope (which they cannot do, because they do not know the needed key), and send the envelope back to your device. Your device opens (decrypts) the envelope. In result, your device has a sheet of paper containing a unique certificate number and the signatures of the servers, but the servers do not know this number.The unique number together with the server's signatures and the ballot is calles >voting certificate<.</p>": [
            "<p><h2>Weitere technische Information</h2>\nDer Wahlschein ist digital von mindestens 2 Servern unterschrieben. Diese Unterschrift führt dazu, dass der Wahlschein bei der Stimmabgabe akzeptiert wird.<br>\nDer Wahlschein enth&auml;lt eine eindeutige Wahlscheinnummer, die nur Ihr Computer kennt - sie wurde von Ihrem Computer erzeugt und verschl&uuml;sselt, bevor die Server den Wahlschein unterschrieben haben, und danach auf Ihrem Computer entschl&uuml;sselt (Man spricht von &quot;Blinded Signature&quot;). Die Server kennen daher die Wahlscheinnummer nicht.<br> \nMan kann sich das so vorstellen:<br>\nIhr Computer schreibt auf den Wahlschein die Wahlscheinnummer, die er sich selbst &quot;ausdenkt&quot; (Zufallszahl). Dieser Wahlschein wird zusammen mit einem Blatt Kohlepapier in einen Umschlag gelegt und an den Server geschickt. \nDer Server unterschreibt außen auf dem Umschlag (wenn Sie wahlberechtigt sind), so dass sich die Unterschrift durch das Kohlepapier auf Ihren Wahlschein &uuml;berträgt. Ohne den Umschlag ge&ouml;ffnet zu haben (was der Server nicht kann, weil er den daf&uuml;r notwendigen Schl&uuml;ssel nicht kennt), schickt er den Brief an Ihren Computer zur&uuml;ck. \nIhr Computer &ouml;ffnet den Umschlag (d.h. entschl&uuml;sselt die Wahlscheinnummer) und h&auml;lt einen vom Server unterschriebenen Wahlschein in der Hand, deren Nummer der Server nicht kennt.  \n</p>"
         ],
         "Please load the voter certification file": [
            "Bitte laden Sie die Datei, in der Ihr Wahlschein gespeichert ist:"
         ],
         "<h2>Voting certificate generated.</h2><p id=\"didSaveButtonsId\">Did you save the voting certificate on your devide?<br><button id=\"savedReturnEnvelope\" onclick=\"page.blinder.onUserDidSaveReturnEnvelope();\" >Yes</button>&emsp;<button id=\"didNotSaveReturnEnvelope\" onclick=\"page.blinder.saveReturnEnvelope();\" >No</button></p><p><ul id=\"howToVoteId\" style=\"display:none\"><li>You got a voting certificate in the form of a webpage file which you saved on your device.</li><li>Please remember the place where you saved it.</li><li>The voting certificate is needed in order to cast the vote. There is no way obaining a new one. Thus, save it securly till the end of the voting.</li><li>In order to cast a vote, open the voting certificate in a web browser. You can do this by double clicking it in the file explorer.</li><li>Everyone who has the voting certificate can use it to cast the vote - thus do not pass it on someoneCasting the vote using the voting certificate is anonymous. That means, as long as you do not help, nobody can find out who sent the vote.</li><li>%s</li></ul></p>": [
            "<h2>Wahlschein erfolgreich erstellt. </h2>\n<p id=\"didSaveButtonsId\">Haben Sie den Wahlschein als Datei auf Ihrem Gerät gespeichert?<br>\n<button id=\"savedReturnEnvelope\" onclick=\"page.blinder.onUserDidSaveReturnEnvelope();\" >Ja</button>\n&emsp;<button id=\"didNotSaveReturnEnvelope\" onclick=\"page.blinder.saveReturnEnvelope();\" >Nein</button>\n</p><p><ul id=\"howToVoteId\" style=\"display:none\">\n<li>Sie haben einen Wahlschein in Form einer Webseiten-Datei erhalten, die Sie auf ihrem Computer gespeichert haben.</li>\n<li>Merken Sie sich bitte, wo Sie die Datei gespeichert haben.</li>\n<li>Der Wahlschein wird benötigt, um die Stimme abzugeben und kann nicht ersetzt werden. Daher wird empfohlen, den Wahlschein bis zum Ende der Abstimmung zu sichern.</li>\n<li>Zum Abstimmen &ouml;ffnen Sie den Wahlschein im Internet-Browser. \nEine M&ouml;glichkeit dazu ist: Klicken Sie im Datei-Explorer doppelt auf die Wahlschein-Datei.</li>\n<li>Der Wahlschein berechtigt zur Stimmabgabe - geben Sie ihn also nicht weiter! Die Stimmabgabe damit ist anonym, d.h. ohne Ihre Mithilfe kann nicht festgestellt werden, von wem die Stimme abgegeben wurde.</li>\n<li>%s</li>\n</ul></p>"
         ],
         "Error: voting certificate data not found": [
            "Fehler: Wahlscheindaten nicht gefunden"
         ],
         "Error: voting certificate data could not be read: JSON decode failed": [
            "Fehler: Wahlscheindaten konnten nicht gelesen werden: JSON decode gescheitert"
         ],
         "The voter certificate is not consistent": [
            "Der Wahlschein ist inkonsistent"
         ],
         "The signature on the vote is correct. This means that the vote is unchanged.": [
            "Die Unterschrift unter der Stimme ist korrekt, d.h. die Stimme wurde nicht verändert."
         ],
         "The signature on the vote is not correct. This means that the vote is changed or the key does not match.": [
            "Die Unterschrift unter der Stimme ist nicht korrekt, d.h. die Stimme wurde verändert oder der Schlüssel passt nicht."
         ],
         "The number of signatures on the voting certificate is not correct. \nRequired number: %d, number in this voting certificate: %d: ": [
            "Fehler beim Überprüfen der Signatur:\nDie Anzahl der Unterschriften unter dem Wahlschein ist nicht korrekt.\nErforderliche Anzahl: %d, Anzahl Unterschriften bei diesem Wahlschein: %d"
         ],
         "The signature by the permission server >%s< for the voting key is correct. This means, the server has confirmed that the according voter is entitled to vote.": [
            "Die Unterschrift von Stimmberechtigungsserver >%s< für den Abstimmungsschlüssel ist korrekt, d.h. der Server hat bestätigt, dass der zugehörige Wähler stimmberechtigt ist."
         ],
         "The signature by permission server >%s< for the voting key is not correct. Either the configuration is wrong or there is a fraud. Please inform the persons responsible for the voting": [
            "Die Unterschrift von Stimmberechtigungsserver >%s< für den Abstimmungsschlüssel ist nicht korrekt. Es liegt entweder eine falsche Konfiguration oder ein Betrugsversuch vor. Bitte die Wahlverantwortlichen informieren."
         ],
         "Error verifying the signature:\n%s": [
            "Fehler beim Überprüfen der Signatur:\n%s"
         ],
         "For voter >%s< the server >%s< returns a different order of signatures than server >%s<.": [
            "Fehler beim überprüfen der Signatur:\nBei Wähler >%s< gibt Server >%s< eine anderen Reihenfolge der Unterschriften an als Server >%s<"
         ],
         "Step 1: Enter voting link": [
            "Schritt 1: Abstimmungslink eingeben"
         ],
         "Step 2: Authorize": [
            "Schritt 2: Autorisieren"
         ],
         "Step 3: Vote": [
            "Schritt 3: Abstimmen"
         ],
         "Enter Voting Link": [
            "Abstimmungslink eingeben"
         ],
         "<p><ul><li>I yet do not have a voting certificate</li><li>For this voting no voting certificate is needed</li><li>I do not know wheather a voting vertificate is needed</li></ul>": [
            "<p><ul><li>Ich habe noch keinen Wahlschein</li><li>f&uuml;r die Wahl wird kein Wahlschein ben&ouml;tigt</li><li>Ich wei&szlig; nicht, ob f&uuml;r die Wahl ein Wahlschein ben&ouml;tigt wird</li></ul>"
         ],
         "Fetch voting properties": [
            "Wahlunterlagen holen"
         ],
         "I already have a voting certificate": [
            "Ich habe bereits einen Wahlschein"
         ],
         "Take part in voting": [
            "An Abstimmung teilnehmen"
         ],
         "It is not possible anymore to create a voting certificate": [
            "Es ist nicht mehr möglich, einen Wahlschein zu erstellen"
         ],
         "The voting requires election module >%s< which is not supported by this client.\nUse a compatible client.": [
            "Die Abstimmung erfordert Modul >%s<, welches von diesem CLient nicht unterstützt wird.\nVerwenden Sie einen kompatiblen Client."
         ],
         "Name of voting:": [
            "Name der Abstimmung:"
         ],
         "The voting requires authorisation module >%s< which is not supported by this client.\nUse a compatible client.": [
            "Die Abstimmung erfordert das Autorisierungsmodul >%s<, welches von diesem Client nicht unterstützt wird.\nVerwenden Sie einen kompatiblen Client."
         ],
         "Generate voting certificate and save it": [
            "Wahlschein erzeugen und speichern"
         ],
         "Voting mode >%s< is not supported by this client": [
            "Abstimmunsmodus >%s< wird vom Client nicht unterstützt"
         ],
         "The voting certificate is not valid": [
            "Der Wahlschein ist nicht gültig"
         ],
         "You directly opened the voting certificate, but you have to save it as file on your device.": [
            "Sie haben den Wahlschein direkt geöffnet. Sie müssen ihn aber als Datei auf Ihrem Gerät speichern."
         ],
         "Error r83g83": [
            "Fehler r83g83"
         ],
         "You can cast your vote from now on and without any time limit.": [
            "Ab sofort können Sie Ihre Stimme ohne zeitliche Einschränkung abgeben."
         ],
         "You can cast your vote from now on until before %s.": [
            "Ab sofort bis vor %s Uhr können Sie Ihre Stimme abgeben."
         ],
         "You can cast your vote from %s until before %s.": [
            "Von %s Uhr bis vor %s Uhr können Sie Ihre Stimme abgeben."
         ],
         "It is not possible anymore to cast your vote.": [
            "Es gibt keine Möglichkeit mehr, Ihre Stimme abzugeben."
         ]
      }
   }
}; 
