if (typeof translations === 'undefined') translations = [];
translations['fr'] = 
{
   "domain": "messages",
   "locale_data": {
      "messages": {
         "": {
            "domain": "messages",
            "plural_forms": "nplurals=2; plural=(n > 1);",
            "lang": "fr"
         },
         "Online Voting: anonymous ballots and traceable": [
            "Vote en ligne: bulletins anonymes et traçable"
         ],
         "Open a new voting": [
            "Ouvrir une nouvelle votation"
         ],
         "Take part in a voting": [
            "Participer à une votation"
         ],
         "Fetch result": [
            "Récupérer les résultats"
         ],
         "Procedure": [
            "Procédure"
         ],
         "Show explanations and technical information": [
            "Afficher les explications et informations techniques"
         ],
         "%s has rejected your request (error no  %d):\n %s": [
            "%s a rejeté votre demande (error no %d):\n%s"
         ],
         "Voting certificate %s": [
            "Certificat de droit de vote %s"
         ],
         "In order to be able to cast your vote, you have to save your voting certificate on your device now": [
            ""
         ],
         "Creating voting certificate": [
            ""
         ],
         "<ul><li>You will get voting certificae in the form of a webpage file as result of this step.</li><li>Please remember where you saved it.</li><li>The voting certificate is neccesary in order to cast the vote. There is no way getting a replacement for it. Thus, save it securely till the end of the voting.</li></ul>": [
            ""
         ],
         "<p><h2>Technical information</h2>The voting certificate is digitally signed by at least two servers. This signatures makes the certificate valid for voting. <br> The voting certificate contains an unique certificate number which is only known by your device - it was generated by your device and encrypted before it was sent and signed by the servers. Your device decrypts thes certificate number together with the server's signatures (This procedure is called &quot;Blinded Signature&quot;). Thus, the servers do not know the certificate number. <br> You can imagine it as follows:<br>  Your device generates a long random number (a unique number) and writes it on a sheet of paper. Your device lays a sheet of carbon-paper on this sheet, puts them together in an envelope, seals it and sends it to the servers. The servers sign on the outside of the envelope, in case you are entitled to vote. By doing so, the signature is transferred to the sheet containing the certificate number because of the carbon-paper. The servers do not open the envelope (which they cannot do, because they do not know the needed key), and send the envelope back to your device. Your device opens (decrypts) the envelope. In result, your device has a sheet of paper containing a unique certificate number and the signatures of the servers, but the servers do not know this number.The unique number together with the server's signatures and the ballot is calles >voting certificate<.</p>": [
            ""
         ],
         "Please load the voter certification file": [
            ""
         ],
         "<h2>Voting certificate generated.</h2><p id=\"didSaveButtonsId\">Did you save the voting certificate on your devide?<br><button id=\"savedReturnEnvelope\" onclick=\"page.blinder.onUserDidSaveReturnEnvelope();\" >Yes</button>&emsp;<button id=\"didNotSaveReturnEnvelope\" onclick=\"page.blinder.saveReturnEnvelope();\" >No</button></p><p><ul id=\"howToVoteId\" style=\"display:none\"><li>You got a voting certificate in the form of a webpage file which you saved on your device.</li><li>Please remember the place where you saved it.</li><li>The voting certificate is needed in order to cast the vote. There is no way obaining a new one. Thus, save it securly till the end of the voting.</li><li>In order to cast a vote, open the voting certificate in a web browser. You can do this by double clicking it in the file explorer.</li><li>Everyone who has the voting certificate can use it to cast the vote - thus do not pass it on someoneCasting the vote using the voting certificate is anonymous. That means, as long as you do not help, nobody can find out who sent the vote.</li><li>%s</li></ul></p>": [
            ""
         ],
         "Error: voting certificate data not found": [
            ""
         ],
         "Error: voting certificate data could not be read: JSON decode failed": [
            ""
         ],
         "The voter certificate is not consistent": [
            ""
         ],
         "The signature on the vote is correct. This means that the vote is unchanged.": [
            ""
         ],
         "The signature on the vote is not correct. This means that the vote is changed or the key does not match.": [
            ""
         ],
         "The number of signatures on the voting certificate is not correct. \nRequired number: %d, number in this voting certificate: %d: ": [
            ""
         ],
         "The signature by the permission server >%s< for the voting key is correct. This means, the server has confirmed that the according voter is entitled to vote.": [
            ""
         ],
         "The signature by permission server >%s< for the voting key is not correct. Either the configuration is wrong or there is a fraud. Please inform the persons responsible for the voting": [
            ""
         ],
         "Error verifying the signature:\n%s": [
            "Erreur vérification de la signature: \n%s"
         ],
         "For voter >%s< the server >%s< returns a different order of signatures than server >%s<.": [
            "Pour le voteur >%s< le serveur >%s< retourne un ordre différent des signatures que le serveur >%s<."
         ],
         "Step 1: Enter voting link": [
            "Etape 1: Entrez le lien de la votation"
         ],
         "Step 2: Authorize": [
            "Etape 2: Autoriser"
         ],
         "Step 3: Vote": [
            "Etape 3: Voter"
         ],
         "Enter Voting Link": [
            "Inserer le lien pour acceder à la votation"
         ],
         "<p><ul><li>I yet do not have a voting certificate</li><li>For this voting no voting certificate is needed</li><li>I do not know wheather a voting vertificate is needed</li></ul>": [
            "<p><ul><li>Je n'ai pas encore un certificat de vote</li><li>Pour cette votation il ne faut pas de certificat  de vote </li><li>I do not know wheather a voting vertificate is needed</li><li>Je ne sais pas si un certificat de vote est nécessaire</ul>"
         ],
         "Fetch voting properties": [
            "Aller chercher les propriétés de vote"
         ],
         "I already have a voting certificate": [
            "Je possède déjà un certificat de vote"
         ],
         "Take part in voting": [
            "Participez a la votation"
         ],
         "It is not possible anymore to create a voting certificate": [
            "Il n'est plus possible de créer un certificat de vote"
         ],
         "The voting requires election module >%s< which is not supported by this client.\nUse a compatible client.": [
            "Le vote exige le module d'éléction  >%s< qui n'est pas pris en charge par ce client.\nUtilisez un client compatible."
         ],
         "Name of voting:": [
            "Nom de la votation:"
         ],
         "The voting requires authorisation module >%s< which is not supported by this client.\nUse a compatible client.": [
            "Le vote exige le module d'autorisation  >%s< qui n'est pas pris en charge par ce client.\nUtilisez un client compatible."
         ],
         "Generate voting certificate and save it": [
            "Générer le certificat de vote et l'enregistrer"
         ],
         "Voting mode >%s< is not supported by this client": [
            "Mode de vote >%s< n'est pas pris en charge par ce client"
         ],
         "The voting certificate is not valid": [
            "Ce certificat de vote n'est pas valable"
         ],
         "You directly opened the voting certificate, but you have to save it as file on your device.": [
            "Vous avez ouvert directement votre certificat de vote, mais vous devez l'enregistrer en tant que fichier sur votre appareil."
         ],
         "Error r83g83": [
            "Erreur r83g83"
         ],
         "You can cast your vote from now on and without any time limit.": [
            "Vous pouvez voter dès maintenant et sans limite de temps."
         ],
         "You can cast your vote from now on until before %s.": [
            "Vous pouvez voter à partir de maintenant jusqu'avant %s."
         ],
         "You can cast your vote from %s until before %s.": [
            "Vous pouvez voter à partir de %s jusqu'avant %s."
         ],
         "It is not possible anymore to cast your vote.": [
            "Il est plus possible de voter."
         ]
      }
   }
}; 
